### ISSUE TITLE
Admins should be able create a password with a code

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-account-http#14]
This comes from the spec the expected feature is:

Add user account
  - Email
  - Temporary code that is emailed to user

currently an admin can create an account by posting an email address to the basePath

this results in a bedrock-account emitting an account.insert event.

My proposal for this feature is:

1. add a query param to the route temp
2. if temp then we need to check permissions are admin ACCOUNT_INSERT
3. if we pass the permissions check then insert the account
4. add password to the account
5. on successful creation email the user (do we have an email solution like send grid? mail chimp?)
6. return 201

the alternative would be to handle this somewhere else via the bedrock account.insert event.

**Comment by aljones15** [comment]
@mattcollier @dlongley @davidlehn 

just a small ping looking to get to work on this today.

**Comment by dlongley** [comment]
@aljones15, I think this should be implemented on the frontend without any special backend code. So the code creates the account and then makes another call to create a password for the user. We prefer to keep the backend as simple as possible.

**Comment by aljones15** [comment]
> @aljones15, I think this should be implemented on the frontend without any special backend code. So the code creates the account and then makes another call to create a password for the user. We prefer to keep the backend as simple as possible.

no issue and thanks for the clarification will do that.

**Comment by dlongley** [comment]
@aljones15, the email issue should be handled separately -- we have a [bedrock-mail](https://github.com/digitalbazaar/bedrock-mail) module that does that. The [bedrock-authn-token](https://github.com/digitalbazaar/bedrock-web-authn-token/tree/implementation) module (responsible for creating authn tokens like passwords) can emit an event that the mail module can setup a listener for and send out an email in response to.

**Comment by dlongley** [comment]
In short -- we don't need to do anything in this module here, we need changes in bedrock-web-account and perhaps bedrock-authn-token (not sure what its status is) ... and we need configuration options in veres-wallet to send out the appropriate mails.

**Comment by aljones15** [comment]
as it stands right now I can in veres-wallet 
1. create account using AccountService
2. use RegisterController
3. I think can just take 1 and 2 and turn admin create account into a single register call with a preset password.
4. however there is still not a way when using RegisterController to specify a special case here where the account and password should be emailed.

**Comment by aljones15** [comment]
add a route to bedrock-web-account that does all of this.
