### ISSUE TITLE
Add the ability to find all accounts associated with an email address

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-account-http#4]
We need the ability to search for accounts by email address. This in turn requires the following features in bedrock-account-http:

1. create a pagination object.

this should help:

https://github.com/digitalbazaar/p3/blob/master/lib/payswarm-auth/services.transaction.js#L730

https://www.dataversity.net/introduction-linked-data-platform/

**Comment by aljones15** [comment]
We are currently using passport so multiple modules exists to support role based claims:

https://www.npmjs.com/package/passport-local-roles

**Comment by aljones15** [comment]
https://github.com/digitalbazaar/bedrock-permission

https://github.com/digitalbazaar/bedrock-express

https://github.com/digitalbazaar/bedrock-passport

**Comment by aljones15** [comment]
https://github.com/digitalbazaar/bedrock-account/blob/master/lib/index.js#L275-L276

https://github.com/digitalbazaar/bedrock-account-http/blob/master/lib/index.js#L77

**Comment by mattcollier** [comment]
@aljones15 test framework here: https://github.com/digitalbazaar/bedrock-account-http/tree/testFramework

normally we *only* do npm install in the `test` folder and then `npm test` there.  

I'll leave it to you to figure out how we use the new eslint config stuff.  It's telling me it can't find the digitalbazaar config.

**Comment by aljones15** [comment]
- [ ] line 42 app.post is registration?
- [ ] line 62 app.get get if an account exists by email
- [ ] line 91 app.patch not implemented yet
- [ ] line 99 app.options no test just returns cors
- [ ] line 100 app.get get account by id
- [ ] line line 111 delete an account not implemented yet
- [ ] add comments explaining each api endpoint
- [ ] change to named functions from lambdas

**Comment by aljones15** [comment]
should be in dev now.
